"""Initial schema: channels, campaigns, creatives, placements, leads, conversions

Revision ID: ef6345c09746
Revises: 
Create Date: 2025-10-01 08:58:47.221607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6345c09746'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('budget_rub', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_cac_rub', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('target_roas', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('channels', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ab_test_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_endpoint', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_code'), 'channels', ['code'], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('utm_source', sa.String(length=50), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_content', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=50), nullable=True),
    sa.Column('utm_term', sa.String(length=100), nullable=True),
    sa.Column('web_id', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('yclients_id', sa.Integer(), nullable=True),
    sa.Column('first_touch_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_first_touch_at'), 'leads', ['first_touch_at'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=True)
    op.create_index(op.f('ix_leads_utm_source'), 'leads', ['utm_source'], unique=False)
    op.create_table('conversions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('channel_code', sa.String(length=20), nullable=True),
    sa.Column('ttp_days', sa.Integer(), nullable=True),
    sa.Column('revenue_rub', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('converted_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversions_booking_id'), 'conversions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_conversions_campaign_id'), 'conversions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_conversions_channel_code'), 'conversions', ['channel_code'], unique=False)
    op.create_index(op.f('ix_conversions_converted_at'), 'conversions', ['converted_at'], unique=False)
    op.create_index(op.f('ix_conversions_lead_id'), 'conversions', ['lead_id'], unique=False)
    op.create_table('creatives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('variant', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=50), nullable=True),
    sa.Column('moderation_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creatives_campaign_id'), 'creatives', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_creatives_id'), 'creatives', ['id'], unique=False)
    op.create_table('placements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('creative_id', sa.UUID(), nullable=True),
    sa.Column('channel_code', sa.String(length=20), nullable=False),
    sa.Column('external_campaign_id', sa.Text(), nullable=True),
    sa.Column('external_ad_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placements_campaign_id'), 'placements', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_placements_channel_code'), 'placements', ['channel_code'], unique=False)
    op.create_index(op.f('ix_placements_creative_id'), 'placements', ['creative_id'], unique=False)
    op.create_index(op.f('ix_placements_id'), 'placements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placements_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_creative_id'), table_name='placements')
    op.drop_index(op.f('ix_placements_channel_code'), table_name='placements')
    op.drop_index(op.f('ix_placements_campaign_id'), table_name='placements')
    op.drop_table('placements')
    op.drop_index(op.f('ix_creatives_id'), table_name='creatives')
    op.drop_index(op.f('ix_creatives_campaign_id'), table_name='creatives')
    op.drop_table('creatives')
    op.drop_index(op.f('ix_conversions_lead_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_converted_at'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_channel_code'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_campaign_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_booking_id'), table_name='conversions')
    op.drop_table('conversions')
    op.drop_index(op.f('ix_leads_utm_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_first_touch_at'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_channels_code'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###