name: Deploy Dev

on:
  push:
    branches: ["develop"]

env:
  PYTHON_VERSION: "3.12"

jobs:
  build-and-deploy:
    if: ${{ secrets.DC_REGISTRY_URL != '' && secrets.DC_DEV_SSH_HOST != '' && secrets.DC_DEV_SSH_KEY != '' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DC_REGISTRY_URL }}
          username: ${{ secrets.DC_REGISTRY_USER }}
          password: ${{ secrets.DC_REGISTRY_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: |
            ${{ secrets.DC_REGISTRY_URL }}/deep-calm-api:dev

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: Dockerfile.frontend
          push: true
          tags: |
            ${{ secrets.DC_REGISTRY_URL }}/deep-calm-frontend:dev

      - name: Deploy to DEV
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DC_DEV_SSH_HOST }}
          username: ${{ secrets.DC_DEV_SSH_USER }}
          key: ${{ secrets.DC_DEV_SSH_KEY }}
          script: |
            docker login ${{ secrets.DC_REGISTRY_URL }} -u ${{ secrets.DC_REGISTRY_USER }} -p ${{ secrets.DC_REGISTRY_PASSWORD }}
            docker pull ${{ secrets.DC_REGISTRY_URL }}/deep-calm-api:dev
            docker pull ${{ secrets.DC_REGISTRY_URL }}/deep-calm-frontend:dev
            cd /opt/deep-calm/dev
            docker compose down
            docker compose up -d
            docker compose exec dc-dev-api alembic upgrade head
*** End Patch
