name: Deploy Dev

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: ${{ secrets.DC_REGISTRY_URL }}
      REGISTRY_USER: ${{ secrets.DC_REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.DC_REGISTRY_PASSWORD }}
      DEV_SSH_HOST: ${{ secrets.DC_DEV_SSH_HOST }}
      DEV_SSH_USER: ${{ secrets.DC_DEV_SSH_USER }}
      DEV_SSH_KEY: ${{ secrets.DC_DEV_SSH_KEY }}

    steps:
      - name: Ensure required secrets are present
        run: |
          if [ -z "$REGISTRY_URL" ] || [ -z "$REGISTRY_USER" ] || [ -z "$REGISTRY_PASSWORD" ] || [ -z "$DEV_SSH_HOST" ] || [ -z "$DEV_SSH_USER" ] || [ -z "$DEV_SSH_KEY" ]; then
            echo "Missing DC_* secrets. Skipping deploy-dev." >&2
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: |
            ${{ env.REGISTRY_URL }}/deep-calm-api:dev

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: Dockerfile.frontend
          push: true
          tags: |
            ${{ env.REGISTRY_URL }}/deep-calm-frontend:dev

      - name: Deploy to DEV
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.DEV_SSH_HOST }}
          username: ${{ env.DEV_SSH_USER }}
          key: ${{ env.DEV_SSH_KEY }}
          script: |
            docker login ${{ env.REGISTRY_URL }} -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }}
            docker pull ${{ env.REGISTRY_URL }}/deep-calm-api:dev
            docker pull ${{ env.REGISTRY_URL }}/deep-calm-frontend:dev
            cd /opt/deep-calm/dev
            docker compose down
            docker compose up -d
            docker compose exec dc-dev-api alembic upgrade head
