name: Deploy Dev

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY_URL: ${{ secrets.DC_REGISTRY_URL }}
      REGISTRY_USER: ${{ secrets.DC_REGISTRY_USER }}
      REGISTRY_PASSWORD: ${{ secrets.DC_REGISTRY_PASSWORD }}
      DEV_SSH_HOST: ${{ secrets.DC_DEV_SSH_HOST }}
      DEV_SSH_USER: ${{ secrets.DC_DEV_SSH_USER }}
      DEV_SSH_KEY: ${{ secrets.DC_DEV_SSH_KEY }}
      RUN_DEPLOY: ${{ secrets.DC_REGISTRY_URL != '' && secrets.DC_REGISTRY_USER != '' && secrets.DC_REGISTRY_PASSWORD != '' && secrets.DC_DEV_SSH_HOST != '' && secrets.DC_DEV_SSH_USER != '' && secrets.DC_DEV_SSH_KEY != '' }}

    steps:
      - name: Check secrets and skip if absent
        if: ${{ env.RUN_DEPLOY != 'true' }}
        run: echo "Required DC_* secrets are missing — deploy-dev skipped."

      - name: Checkout
        if: ${{ env.RUN_DEPLOY == 'true' }}
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        if: ${{ env.RUN_DEPLOY == 'true' }}
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        if: ${{ env.RUN_DEPLOY == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build and push API image
        if: ${{ env.RUN_DEPLOY == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: |
            ${{ env.REGISTRY_URL }}/deep-calm-api:dev

      - name: Build and push Frontend image
        if: ${{ env.RUN_DEPLOY == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.frontend
          push: true
          tags: |
            ${{ env.REGISTRY_URL }}/deep-calm-frontend:dev

      - name: Deploy to DEV
        if: ${{ env.RUN_DEPLOY == 'true' }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.DEV_SSH_HOST }}
          username: ${{ env.DEV_SSH_USER }}
          key: ${{ env.DEV_SSH_KEY }}
          script: |
            set -euo pipefail
            docker login ${{ env.REGISTRY_URL }} -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }}
            docker pull ${{ env.REGISTRY_URL }}/deep-calm-api:dev
            docker pull ${{ env.REGISTRY_URL }}/deep-calm-frontend:dev
            docker tag ${{ env.REGISTRY_URL }}/deep-calm-api:dev deep-calm-api:dev
            docker tag ${{ env.REGISTRY_URL }}/deep-calm-frontend:dev deep-calm-frontend:dev
            cd /opt/deep-calm/dev
            docker compose down
            docker compose up -d
            for i in $(seq 1 30); do
              if docker compose exec -T dc-db pg_isready -U dc -d dc_dev >/dev/null 2>&1; then
                echo "dc-db is accepting connections"
                break
              fi
              if [ "$i" -eq 30 ]; then
                echo "Postgres (dc-db) did not become ready" >&2
                exit 1
              fi
              echo "Waiting for dc-db to become ready ($i/30)..."
              sleep 5
            done
            for i in $(seq 1 30); do
              status=$(docker inspect -f '{{.State.Status}}' dc-dev-api 2>/dev/null || true)
              health=$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' dc-dev-api 2>/dev/null || true)
              if [ "$status" = "running" ] && { [ "$health" = "healthy" ] || [ "$health" = "none" ] || [ "$health" = "starting" ]; }; then
                echo "dc-dev-api is $status (health: $health)"
                break
              fi
              if [ "$i" -eq 30 ]; then
                echo "dc-dev-api did not become ready" >&2
                exit 1
              fi
              echo "Waiting for dc-dev-api to become ready ($i/30)..."
              sleep 5
            done
            docker compose exec -T dc-api alembic upgrade head
