name: PR Checks

on:
  pull_request:
    branches: ["main", "develop"]

env:
  PYTHON_VERSION: "3.12"
  NODE_VERSION: "20"

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: dc_ci
          POSTGRES_USER: dc
          POSTGRES_PASSWORD: dcpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U dc -d dc_ci"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint

      - name: Test frontend
        working-directory: frontend
        run: npm run test -- --run

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install backend dependencies
        run: pip install -r requirements.txt

      - name: Run backend tests
        env:
          DC_DATABASE_URL: postgresql://dc:dcpass@localhost:5432/dc_ci
          DATABASE_URL: postgresql://dc:dcpass@localhost:5432/dc_ci
          DC_REDIS_URL: redis://localhost:6379/0
        run: pytest

      - name: Export OpenAPI schema
        env:
          DC_DATABASE_URL: postgresql://dc:dcpass@localhost:5432/dc_ci
          DATABASE_URL: postgresql://dc:dcpass@localhost:5432/dc_ci
          DC_REDIS_URL: redis://localhost:6379/0
        run: python scripts/export_openapi.py

      - name: Ensure OpenAPI schema committed
        run: |
          git diff --exit-code cortex/APIs/openapi.json

      - name: Upload coverage (optional)
        if: false
        run: echo "placeholder"
